### ISSUE TITLE
Placing EMC crafter in world hangs MC.

### ISSUE THREAD

**Issue by Vahtera** [Bartz24/RefinedExchange#12]
Refined Exchange: 2.1.0
Refined Storage: 1.6.12
ProjectE: 1.3.2h
Minecraft: 1.12.2
Forge: 14.23.5.2796

(FTB Direwolf20 modpack, with modifications)

Everything worked 100%, added Refined Exchange 2.1.0 and loaded world: no problems.
Crafter a single EMC liquifier and EMC Crafter: no problems.
Taught then to the ProjectE table and got a stack of crafters: no problems.
Placed the EMC liquifier in the world next to RS controller: no problems.
Connected a cable to it, no problems:
Placed an EMC crafter next to that cable: MC hangs up. No errors, no crashes, just hang. 
Killed process, started modpack again. Modpack starts fine, but when loading the world, MC hangs at "Building Terrain" and goes to "Not Responding" state.

**Comment by Bartz24** [comment]
Thanks!
The game did crash on me when i tested again, so I hope my fix works for your issue too!
Update coming very shortly!
