### ISSUE TITLE
Server Side Crash 2.0.1

### ISSUE THREAD

**Issue by walker-dev** [Bartz24/RefinedExchange#3]
[crash-2018-08-05_11.10.08-server.txt](https://github.com/Bartz24/RefinedExchange/files/2260170/crash-2018-08-05_11.10.08-server.txt)

**Comment by deusversus** [comment]
I believe this is the same crash you're getting. Just dropping another log in incase it helps; will bookmark this and check back for suggestions.

[crash-2018-08-05_17.19.01-server.txt](https://github.com/Bartz24/RefinedExchange/files/2260709/crash-2018-08-05_17.19.01-server.txt)

**Comment by Bartz24** [comment]
Fixed in 2.0.2
