### ISSUE TITLE
EMC Liquifier causes crash

### ISSUE THREAD

**Issue by deusversus** [Bartz24/RefinedExchange#4]
[crash-2018-08-06_17.35.38-server.txt](https://github.com/Bartz24/RefinedExchange/files/2264201/crash-2018-08-06_17.35.38-server.txt)

I put an item in the EMC Liquifier and it crashed the server.

**Comment by Bartz24** [comment]
According to the crash log, you're using ProjectE version 1.3.0

you need to be using ProjectE version 1.3.1 beta (stated on the mod page and changelog :D). 1.3.0 is incompatible with Refined Exchange
