### ISSUE TITLE
Crash when using EMC liquifier

### ISSUE THREAD

**Issue by onyxromero** [Bartz24/RefinedExchange#5]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.12.2-0.5.35.jar)
  ForgelinPlugin (Forgelin-1.7.4.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  EECore (ExpandedEquivalence-1.12.2-10a.jar)
  HCASM (HammerCore-1.12.2-2.0.1.2.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-84.jar)
  GottaGoFastLoader (gottagofast-1.1.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 8/7/18 12:55 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: moze_intel.projecte.api.proxy.IEMCProxy.getValue(Lnet/minecraft/item/ItemStack;)J
	at com.bartz24.refinedexchange.features.network.NetworkNodeLiquifier.update(NetworkNodeLiquifier.java:54)
	at com.raoulvdberge.refinedstorage.apiimpl.network.NetworkNodeListener.onWorldTick(NetworkNodeListener.java:23)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_769_NetworkNodeListener_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:273)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:776)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2867767264 bytes (2734 MB) / 6408896512 bytes (6112 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2739 Optifine OptiFine_1.12.2_HD_U_E1 118 mods loaded, 118 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State       | ID                                | Version                | Source                                               | Signature                                |
	|:----------- |:--------------------------------- |:---------------------- |:---------------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAAAA | minecraft                         | 1.12.2                 | minecraft.jar                                        | None                                     |
	| UCHIJAAAAAA | mcp                               | 9.42                   | minecraft.jar                                        | None                                     |
	| UCHIJAAAAAA | FML                               | 8.0.99.99              | forge-1.12.2-14.23.4.2739.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAAAA | forge                             | 14.23.4.2739           | forge-1.12.2-14.23.4.2739.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAAAA | gottagofast                       | 1.1                    | gottagofast-1.1.jar                                  | None                                     |
	| UCHIJAAAAAA | quarryplus                        | 0.9.10                 | AdditionalEnchantedMiner-1.12.2-0.9.10-universal.jar | 617a4e95f0af9de5402bb9883abe0f53a6bfa230 |
	| UCHIJAAAAAA | codechickenlib                    | 3.2.0.345              | CodeChickenLib-1.12.2-3.2.0.345-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAAAA | avaritia                          | 3.2.0                  | Avaritia-1.12.2-3.2.0.25-universal.jar               | None                                     |
	| UCHIJAAAAAA | avaritiatweaks                    | 1.12.2-1.1             | AvaritiaTweaks-1.12.2-1.1.jar                        | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
	| UCHIJAAAAAA | baubles                           | 1.5.2                  | Baubles-1.12-1.5.2.jar                               | None                                     |
	| UCHIJAAAAAA | bedrockminer                      | 1.0.3                  | Bedrock+Miner+1.12.2+by+XxRexRaptorxX+(v.1.0.3).jar  | None                                     |
	| UCHIJAAAAAA | biomesoplenty                     | 7.0.1.2384             | BiomesOPlenty-1.12.2-7.0.1.2384-universal.jar        | None                                     |
	| UCHIJAAAAAA | blockdropstweaker                 | 2.4                    | BlockDropsTweaker-1.12.2-2.4.jar                     | None                                     |
	| UCHIJAAAAAA | redstoneflux                      | 2.0.2                  | RedstoneFlux-1.12-2.0.2.3-universal.jar              | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAAAA | brandonscore                      | 2.4.4                  | BrandonsCore-1.12.2-2.4.4.173-universal.jar          | None                                     |
	| UCHIJAAAAAA | capsule                           | 1.12.2-3.1.69          | Capsule-1.12.2-3.1.69.jar                            | None                                     |
	| UCHIJAAAAAA | chameleon                         | 1.12-4.1.3             | Chameleon-1.12-4.1.3.jar                             | None                                     |
	| UCHIJAAAAAA | chesttransporter                  | 2.8.8                  | ChestTransporter-1.12.2-2.8.8.jar                    | None                                     |
	| UCHIJAAAAAA | chickenchunks                     | 2.4.0.70               | ChickenChunks-1.12-2.4.0.70-universal.jar            | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAAAA | ctm                               | MC1.12.2-0.3.2.18      | CTM-MC1.12.2-0.3.2.18.jar                            | None                                     |
	| UCHIJAAAAAA | chisel                            | MC1.12.2-0.2.0.31      | Chisel-MC1.12.2-0.2.0.31.jar                         | None                                     |
	| UCHIJAAAAAA | cofhcore                          | 4.5.3                  | CoFHCore-1.12.2-4.5.3.20-universal.jar               | None                                     |
	| UCHIJAAAAAA | cofhworld                         | 1.2.0                  | CoFHWorld-1.12.2-1.2.0.5-universal.jar               | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAAAA | combustfish                       | 1.0.3.2                | combustfish-1.12.2-1.0.3.2.jar                       | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UCHIJAAAAAA | placebo                           | 1.4.0                  | Placebo-1.12.2-1.4.0.jar                             | None                                     |
	| UCHIJAAAAAA | singularities                     | 2.3.1                  | Singularities-1.12.2-2.3.1.jar                       | None                                     |
	| UCHIJAAAAAA | crafttweaker                      | 4.1.9                  | CraftTweaker2-1.12-4.1.9.jar                         | None                                     |
	| UCHIJAAAAAA | ctgui                             | 1.0.0                  | CraftTweaker2-1.12-4.1.9.jar                         | None                                     |
	| UCHIJAAAAAA | mtlib                             | 3.0.5                  | MTLib-3.0.5.jar                                      | None                                     |
	| UCHIJAAAAAA | modtweaker                        | 4.0.12                 | modtweaker-4.0.12.jar                                | None                                     |
	| UCHIJAAAAAA | jei                               | 4.11.0.206             | jei_1.12.2-4.11.0.206.jar                            | None                                     |
	| UCHIJAAAAAA | crafttweakerjei                   | 2.0.2                  | CraftTweaker2-1.12-4.1.9.jar                         | None                                     |
	| UCHIJAAAAAA | cucumber                          | 1.1.1                  | Cucumber-1.12.2-1.1.1.jar                            | None                                     |
	| UCHIJAAAAAA | cyberware                         | 0.2.10.12              | cyberware-1.12.2-0.2.10.12.jar                       | 67a0e286dc0d4b502f3c92ac20b953517b52d0a9 |
	| UCHIJAAAAAA | endercore                         | 1.12.2-0.5.35          | EnderCore-1.12.2-0.5.35.jar                          | None                                     |
	| UCHIJAAAAAA | thermalfoundation                 | 2.5.0                  | ThermalFoundation-1.12.2-2.5.0.19-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAAAA | draconicevolution                 | 2.3.13                 | Draconic-Evolution-1.12.2-2.3.13.306-universal.jar   | None                                     |
	| UCHIJAAAAAA | thermalexpansion                  | 5.5.0                  | ThermalExpansion-1.12.2-5.5.0.29-universal.jar       | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAAAA | enderio                           | 5.0.29                 | EnderIO-1.12.2-5.0.29.jar                            | None                                     |
	| UCHIJAAAAAA | mantle                            | 1.12-1.3.2.24          | Mantle-1.12-1.3.2.24.jar                             | None                                     |
	| UCHIJAAAAAA | projecte                          | 1.12-PE1.3.0           | ProjectE-1.12-PE1.3.0.jar                            | None                                     |
	| UCHIJAAAAAA | enderiointegrationtic             | 5.0.29                 | EnderIO-1.12.2-5.0.29.jar                            | None                                     |
	| UCHIJAAAAAA | tconstruct                        | 1.12.2-2.10.1.87       | TConstruct-1.12.2-2.10.1.87.jar                      | None                                     |
	| UCHIJAAAAAA | tesla                             | 1.0.63                 | Tesla-1.12.2-1.0.63.jar                              | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAAAA | p455w0rdslib                      | 2.0.29                 | p455w0rdslib-1.12-2.0.29.jar                         | None                                     |
	| UCHIJAAAAAA | theoneprobe                       | 1.4.22                 | theoneprobe-1.12-1.4.22.jar                          | None                                     |
	| UCHIJAAAAAA | danknull                          | 1.4.33                 | DankNull-1.12-1.4.33.jar                             | None                                     |
	| UCHIJAAAAAA | enderiobase                       | 5.0.29                 | EnderIO-1.12.2-5.0.29.jar                            | None                                     |
	| UCHIJAAAAAA | enderioconduits                   | 5.0.29                 | EnderIO-1.12.2-5.0.29.jar                            | None                                     |
	| UCHIJAAAAAA | enderioconduitsappliedenergistics | 5.0.29                 | EnderIO-1.12.2-5.0.29.jar                            | None                                     |
	| UCHIJAAAAAA | refinedstorage                    | 1.6.3                  | refinedstorage-1.6.3.jar                             | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| UCHIJAAAAAA | enderioconduitsopencomputers      | 5.0.29                 | EnderIO-1.12.2-5.0.29.jar                            | None                                     |
	| UCHIJAAAAAA | enderioconduitsrefinedstorage     | 5.0.29                 | EnderIO-1.12.2-5.0.29.jar                            | None                                     |
	| UCHIJAAAAAA | enderiointegrationforestry        | 5.0.29                 | EnderIO-1.12.2-5.0.29.jar                            | None                                     |
	| UCHIJAAAAAA | enderiointegrationticlate         | 5.0.29                 | EnderIO-1.12.2-5.0.29.jar                            | None                                     |
	| UCHIJAAAAAA | enderiomachines                   | 5.0.29                 | EnderIO-1.12.2-5.0.29.jar                            | None                                     |
	| UCHIJAAAAAA | enderiopowertools                 | 5.0.29                 | EnderIO-1.12.2-5.0.29.jar                            | None                                     |
	| UCHIJAAAAAA | enderstorage                      | 2.4.2.126              | EnderStorage-1.12.2-2.4.2.126-universal.jar          | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAAAA | wanionlib                         | 1.12.2-1.5             | WanionLib-1.12.2-1.5.jar                             | None                                     |
	| UCHIJAAAAAA | eternalsingularity                | 1.12.2-.1.0.5          | eternalsingularity-1.12.2-1.0.5.jar                  | None                                     |
	| UCHIJAAAAAA | mekanism                          | 1.12.2-9.4.13.349      | Mekanism-1.12.2-9.4.13.349.jar                       | None                                     |
	| UCHIJAAAAAA | immersiveengineering              | 0.12-84                | ImmersiveEngineering-0.12-84.jar                     | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHIJAAAAAA | exchangers                        | 1.12.2-2.7.3           | Exchangers-1.12.2-2.7.3.jar                          | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
	| UCHIJAAAAAA | hammercore                        | 2.0.1.2                | HammerCore-1.12.2-2.0.1.2.jar                        | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| UCHIJAAAAAA | expequiv                          | 10a                    | ExpandedEquivalence-1.12.2-10a.jar                   | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| UCHIJAAAAAA | extrautils2                       | 1.0                    | extrautils2-1.12-1.7.6.jar                           | None                                     |
	| UCHIJAAAAAA | fastleafdecay                     | v14                    | FastLeafDecay-v14.jar                                | None                                     |
	| UCHIJAAAAAA | finite-water-control              | 1.0                    | finite-water-control-1.12-1.0.jar                    | None                                     |
	| UCHIJAAAAAA | forgelin                          | 1.7.4                  | Forgelin-1.7.4.jar                                   | None                                     |
	| UCHIJAAAAAA | forgemultipartcbe                 | 2.4.2.60               | ForgeMultipart-1.12.2-2.4.2.60-universal.jar         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAAAA | microblockcbe                     | 2.4.2.60               | ForgeMultipart-1.12.2-2.4.2.60-universal.jar         | None                                     |
	| UCHIJAAAAAA | minecraftmultipartcbe             | 2.4.2.60               | ForgeMultipart-1.12.2-2.4.2.60-universal.jar         | None                                     |
	| UCHIJAAAAAA | immersivepetroleum                | 1.1.9                  | immersivepetroleum-1.12.2-1.1.9.jar                  | None                                     |
	| UCHIJAAAAAA | teslacorelib                      | 1.0.15                 | tesla-core-lib-1.12.2-1.0.15.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAAAA | industrialforegoing               | 1.12.2-1.12.2          | industrialforegoing-1.12.2-1.10.4-187.jar            | None                                     |
	| UCHIJAAAAAA | infinity                          | 0.10                   | Infinity-0.10.jar                                    | None                                     |
	| UCHIJAAAAAA | mysticalagriculture               | 1.6.12                 | mysticalagriculture-1.12-1.6.12.jar                  | None                                     |
	| UCHIJAAAAAA | mysticalagradditions              | 1.2.8                  | mysticalagradditions-1.12-1.2.8.jar                  | None                                     |
	| UCHIJAAAAAA | natura                            | 1.12.2-4.3.2.49        | natura-1.12.2-4.3.2.49.jar                           | None                                     |
	| UCHIJAAAAAA | integrationforegoing              | 1.12.2-1.7.2           | IntegrationForegoing-1.12.2-1.7.2.jar                | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
	| UCHIJAAAAAA | jaopca                            | 1.12.2-2.2.8.91        | JAOPCA-1.12.2-2.2.8.91.jar                           | None                                     |
	| UCHIJAAAAAA | oredictinit                       | 1.12.2-2.2.1.68        | JAOPCA-1.12.2-2.2.8.91.jar                           | None                                     |
	| UCHIJAAAAAA | kleeslabs                         | 5.4.10                 | KleeSlabs_1.12.2-5.4.10.jar                          | None                                     |
	| UCHIJAAAAAA | mystcraft                         | 0.13.6.00              | mystcraft-1.12.2-0.13.6.00.jar                       | None                                     |
	| UCHIJAAAAAA | gbook                             | 2.6.5                  | Guidebook-1.12.2-2.6.5.jar                           | None                                     |
	| UCHIJAAAAAA | ltta                              | 1.2.3                  | ltta-1.12.2-1.2.3.jar                                | None                                     |
	| UCHIJAAAAAA | mekanismgenerators                | 9.4.11                 | MekanismGenerators-1.12.2-9.4.13.349.jar             | None                                     |
	| UCHIJAAAAAA | mekanismtools                     | 9.4.11                 | MekanismTools-1.12.2-9.4.13.349.jar                  | None                                     |
	| UCHIJAAAAAA | mob_grinding_utils                | 0.3.7                  | MobGrindingUtils-0.3.7.jar                           | None                                     |
	| UCHIJAAAAAA | mystagradcompat                   | 1.2                    | mystagradcompat-1.2.jar                              | None                                     |
	| UCHIJAAAAAA | netherendingores                  | 1.12.2-1.2             | Netherending-Ores-1.12.2-1.2.jar                     | None                                     |
	| UCHIJAAAAAA | terracore                         | 2.1.13                 | TerraCore-1.12-2.1.13.jar                            | None                                     |
	| UCHIJAAAAAA | netherutils                       | 1.12-1.4.22            | NetherUtils-1.12-1.4.22.jar                          | None                                     |
	| UCHIJAAAAAA | recipehandler                     | 0.10                   | NoMoreRecipeConflict-0.10(1.12.2).jar                | None                                     |
	| UCHIJAAAAAA | norecipebook                      | 1.2.1                  | noRecipeBook_v1.2.2formc1.12.2.jar                   | None                                     |
	| UCHIJAAAAAA | nuclearcraft                      | 2.10p                  | NuclearCraft-2.10p--1.12.2.jar                       | None                                     |
	| UCHIJAAAAAA | omlib                             | 3.0.0-143              | omlib-1.12.2-3.0.0-143.jar                           | None                                     |
	| UCHIJAAAAAA | openmodularturrets                | 3.0.0-248              | openmodularturrets-1.12.2-3.0.0-248.jar              | None                                     |
	| UCHIJAAAAAA | progressivealchemy                | 1.12.2-1.0.1           | progressivealchemy-1.12.2-1.0.1.jar                  | None                                     |
	| UCHIJAAAAAA | randomtweaks                      | 1.12.2-2.1.2.1         | randomtweaks-1.12.2-2.1.2.1.jar                      | None                                     |
	| UCHIJAAAAAA | reborncore                        | 3.9.3.324              | RebornCore-1.12.2-3.9.3.324-universal.jar            | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UCHIJAAAAAA | rebornstorage                     | 1.0.0                  | RebornStorage-1.12.2-3.2.1.63.jar                    | None                                     |
	| UCHIJAAAAAA | refined_avaritia                  | 2.0                    | refined_avaritia-1.12.2-2.0.jar                      | None                                     |
	| UCHIJAAAAAA | refinedexchange                   | 2.0.2                  | refinedexchange-2.0.2.jar                            | None                                     |
	| UCHIJAAAAAA | refinedstorageaddons              | 0.4.1                  | refinedstorageaddons-0.4.1.jar                       | None                                     |
	| UCHIJAAAAAA | simplyenchanting                  | 1.0.3                  | SimplyEnchanting-1.12-1.0.3.jar                      | None                                     |
	| UCHIJAAAAAA | thermaldynamics                   | 2.5.1                  | ThermalDynamics-1.12.2-2.5.1.14-universal.jar        | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAAAA | simplyjetpacks                    | 2.2.7.45               | SimplyJetpacks2-1.12.2-2.2.7.45.jar                  | None                                     |
	| UCHIJAAAAAA | storagedrawers                    | 1.12-5.3.5             | StorageDrawers-1.12.2-5.3.6.jar                      | None                                     |
	| UCHIJAAAAAA | tinkertoolleveling                | 1.12-1.0.4.DEV.5d716b9 | TinkerToolLeveling-1.12-1.0.4.jar                    | None                                     |
	| UCHIJAAAAAA | topaddons                         | 1.12.2-1.6.0           | topaddons-1.12.2-1.6.0.jar                           | None                                     |
	| UCHIJAAAAAA | torcherino                        | 7.2                    | torcherino-7.2.jar                                   | None                                     |
	| UCHIJAAAAAA | translocators                     | 2.5.0.70               | Translocators-1.12.2-2.5.0.70-universal.jar          | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAAAA | virtualmachines                   | 1.12.2-1.0.0.2-CUSTOM  | VirtualMachines-1.12.2-1.0.0.4.jar                   | None                                     |
	| UCHIJAAAAAA | xaerominimap                      | 1.14.9.1               | Xaeros_Minimap_1.14.9.1_Forge_1.12.jar               | None                                     |
	| UCHIJAAAAAA | teslacorelib_registries           | 1.0.15                 | tesla-core-lib-1.12.2-1.0.15.jar                     | None                                     |
	| UCHIJAAAAAA | unidict                           | 1.12.2-2.5f            | UniDict-1.12.2-2.5f.jar                              | None                                     |
	| UCHIJAAAAAA | wrapup                            | 1.12-1.1.3             | WrapUp-1.12-1.1.3.jar                                | None                                     |

	Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.12.2-0.5.35.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
ForgelinPlugin (Forgelin-1.7.4.jar)
  
CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  team.chisel.ctm.client.asm.CTMTransformer
EECore (ExpandedEquivalence-1.12.2-10a.jar)
  com.zeitheron.expequiv.core.EETransformer
HCASM (HammerCore-1.12.2-2.0.1.2.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-84.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
GottaGoFastLoader (gottagofast-1.1.jar)
  com.thiakil.gottagofast.coremod.GottaGoFastASMTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
OreDictionary Info: Registered 3797 names; 5266 stacks.
Configuration Info: IyBDb25maWd1cmF0aW9uIGZpbGUNCg0KY2xpZW50IHsNCiAgICAjIFNob3VsZCBIYW1tZXIgQ29yZSByZXBsYWNlIGVuY2hhbnRtZW50IGdsaW50IGNvbG9yIHdpdGggbW9yZSBtYXRjaGluZyBjb2xvcnMgZm9yIHNvbWUgdmFuaWxsYSBpdGVtcz8gW2RlZmF1bHQ6IHRydWVdDQogICAgQjoiQ3VzdG9tIEVuY2hhbnRtZW50IENvbG9ycyBmb3IgVmFuaWxsYSBJdGVtcyI9dHJ1ZQ0KDQogICAgIyBTaG91bGQgSGFtbWVyIENvcmUgcG9ydGZvcndhcmQgeW91ciBsb2NhbCB3b3JsZCB3aGVuIHlvdSBzaGFyZSB3aXRoIGl0IHRvIExBTj8NCiAgICAjIFRoaXMgZmVhdHVyZSBkb2Vzbid0IHdvcmsgb24gYWxsIGNsaWVudHMsIHlvdSBhcmUgZ29pbmcgdG8gZ2V0IGEgbWVzc2FnZSBpbiBjaGF0IGlmIGl0IHdhcyBzdWNjZXNzZnVsL3Vuc3VjY2Vzc2Z1bCBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJMQU4gVVBuUCI9dHJ1ZQ0KDQogICAgIyBSZXBsYWNlIHZhbmlsbGEgZnVybmFjZSBhbmQgYnJld2luZyBzdGFuZCBwcm9ncmVzcyBiYXJzIHRvIHVzZSBzbW9vdGggcmVuZGVyaW5nPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJTbW9vdGggVmFuaWxsYSBHdWlzIj10cnVlDQp9DQoNCg0KaXdyZW5jaCB7DQogICAgIyBXaGF0IGlzIHRoZSBjb2xvciB3aGVuIHRoZSBob3ZlcmVkIGJsb2NrIGlzIHdyZW5jaGFibGU/IChjb2xvciBlbmNvZGVkIGluIGhleCBmb3JtIHN1Y2ggYXMgUlJHR0JCKQ0KICAgIFM6R3JlZW49MjJGRjIyDQoNCiAgICAjIFdoYXQgaXMgdGhlIGNvbG9yIHdoZW4gdGhlIGhvdmVyZWQgYmxvY2sgaXMgTk9UIHdyZW5jaGFibGU/IChjb2xvciBlbmNvZGVkIGluIGhleCBmb3JtIHN1Y2ggYXMgUlJHR0JCKQ0KICAgIFM6UmVkPUZGMjIyMg0KfQ0KDQoNCiJ2YW5pbGxhIGltcHJvdmVtZW50cyIgew0KICAgICMgU2hvdWxkIEhhbW1lciBDb3JlIGZvcmNlLXNwYXduIEVuZGVyIERyYWdvbiBFZ2cgb24gRW5kZXIgRHJhZ29uIGRlYXRoPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJBbHdheXMgU3Bhd24gRHJhZ29uIEVnZyI9dHJ1ZQ0KfQ0KDQoNCg==
Pastebin Connection: Okay.
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.9.3.324
		Runtime Debofucsation 1
		RenderEngine: 1
	Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.

**Comment by Bartz24** [comment]
You need to be using ProjectE version 1.3.1 beta

**Comment by Bartz24** [comment]
i just noticed the mod page and changelog said ProjectE 1.3.0 was ok. It was a typo. 

Sorry for the confusion!

**Comment by onyxromero** [comment]
It's fine. Tbh, I got confused by the two different mod versions anyways. I just had assumed one was the same as the other. Lol

**Comment by 016Nojr** [comment]
@Bartz24 Just had the same crash happen

**Comment by Bartz24** [comment]
what versions of ProjectE, Refined Storage, and Refined Exchange are you using?

**Comment by 016Nojr** [comment]
nvm, I thought your comment earlier in the issue meant version 1.3.0 of Project E was ok, not that it meant that 1.3.0 was a mistype. Sorry, 1.3.1 is good

**Comment by Bartz24** [comment]
cool. yeah 1.3.1 is the version that works
