### ISSUE TITLE
No matter what I try to craft in the Refined Storage Grid with EMC, the grid doesn't craft it

### ISSUE THREAD

**Issue by onyxromero** [Bartz24/RefinedExchange#6]
I go to check the Crafting Monitor and it says that it's processing the EMC into for example a Diamond and it never consumes any EMC to produce the Diamond, therefore the Diamond doesn't get crafted. Is there anything I'm doing wrong?

**Comment by Bartz24** [comment]
I just tested it. It works fine.

Only thing I could think of is you don't have enough fluid and/or item storage in your system.

**Comment by Tenavin** [comment]
I was able to reproduce this issue by installing incompatible versions of Refined Storage and RefinedExchange. And then updating them to compatible versions. Did you happen to do something similar Unjustifiable?
