### ISSUE TITLE
Crash when placing the EMC liquifier or the EMC crafter

### ISSUE THREAD

**Issue by RobinNightWing** [Bartz24/RefinedExchange#7]
I crash upon placing either of the 2 blocks added from this mod.

Refined Storage- 1.6
ProjectE- 1.3.1
RefinedExchange- 2.0.2

Crash report-
[crash-2018-08-13_23.27.28-client.txt](https://github.com/Bartz24/RefinedExchange/files/2286914/crash-2018-08-13_23.27.28-client.txt)

**Comment by Bartz24** [comment]
I really apologize...but I thought Refined Storage 1.6.0 worked...
something must have changed after that version.

I know Refined Storage 1.6.3 works for sure.
Sorry again!
